### ISSUE TITLE
Tcp服务项目上开启HTTP测试用于测试，总是报警告

### ISSUE THREAD

**Issue by zzjzzb** [luoxiaojun1992/yii2-tars-demo#4]
项目是提供TCP服务的，但用于测试想添加想对应的HTTP服务，params文件如下：
 'tars' =>
        array(
            'registries' =>
                array(),
            'services' =>
                array(
                    'contentSafetyObj' =>
                        array(
                            'protocolName' => 'http',
                            'serverType' => 'http',
                            'namespaceName' => 'Lxj\\Yii2\\Tars\\',
                            'monitorStoreConf' =>
                                array(
                                    'className' => 'Tars\\monitor\\cache\\SwooleTableStoreCache',
                                    'config' =>
                                        array(
                                            'size' => 40960,
                                        ),
                                ),
                        ),
                    'ConfigObj' =>
                        array(
                            'protocolName' => 'tars',
                            'serverType' => 'tcp',
                            'home-api' => '\\app\\tars\\servant\\Miqu\\ConfigHandlerService\\ConfigObj\\ConfigHandlerServiceServant',
                            'home-class' => '\\app\\tars\\impl\\configHandlerImpl',
                        ),
                ),

//        array (
//      'appName' => 'Miqu',
//      'serverName' => 'ConfigHandlerService',
//      'objName' => 'ConfigObj',
//      'withServant' => false,
//      'tarsFiles' =>
//      array (
//        0 => './configHandler.tars',
//      ),
//      'dstPath' => '../src/tars/servant',
//      'namespacePrefix' => 'app\\tars\\servant',
//    ),
            'proto' => array(
                'appName' => 'Miqu',
                'serverName' => 'ContentSafetyService',
                'objName' => 'contentSafetyObj',
                //'withServant' => true,
                //'tarsFiles' =>
                //array (
                // 0 => './example.tars',
                //),
                //'dstPath' => '../src/tars/servant',
                //'namespacePrefix' => 'app\\tars\\servant',
            ),
            'log_level' => ['info'],
            'log_interval' => 1,
        ),
发布成功后，会一直报：
WARNING	swManager_loop(:354): wait() failed. Error: No child processes[10]
由于报的速度太快，一个上午可以达几十G，请问这个有人知道处理吗？

**Comment by luoxiaojun1992** [comment]
1. 请执行 ps 查看swoole进程是否已经启动
2. 请查看 /usr/local/app/tars 目录下项目日志文件报错信息
3. 请查看平台自带的tars服务是否都正常启动
4. 请查看项目框架的log是否有报错信息

**Comment by luoxiaojun1992** [comment]
我将结束这个问题。如果您有任何问题，请随时重新讨论这个问题。

**Comment by luoxiaojun1992** [comment]
I will close this issue. If you have any question else, please feel free to reopen this issue.
